#!/bin/bash

if [[ "$1" == "lib" ]]
then

    if [[ "$2" == "install" ]]
    then
        ./mvnw clean source:jar install
        OK=1
    fi
    if [[ "$2" == "deploy" ]]
    then
        ./mvnw clean deploy
        OK=1
    fi
    if [[ "$2" == "sign" ]]
    then
        gpg -ab target/sysagent-0.0.3.jar
        gpg -ab target/sysagent-0.0.3-javadoc.jar
        gpg -ab target/sysagent-0.0.3-sources.jar
        OK=1
    fi

    if [[ "$2" == "mvnw" ]]
    then
        mvn -N wrapper:wrapper
        OK=1
    fi
fi

if [[ "$1" == "" ]]
then
    echo run
    echo "    lib"
    echo "        install             Build, package and install the library to the local repo"
    echo "        deploy              Build, package, sign and deploy the library to maven central"
    echo "        mvnw                Install maven wrapper"
    echo "        sign                Sign the deployable jar files"
    OK=1
fi

if [[ $OK != 1 ]]
then
    echo "Invalid command - run $1 $2"
fi